# Generated by Django 4.2.8 on 2023-12-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=60)),
                ('date_action', models.CharField(max_length=60)),
                ('criterion', models.CharField(max_length=100)),
            ],
        ),
    ]
