# Generated by Django 4.2.8 on 2023-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patners_name', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('organization', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
